# Generated by Django 5.1.3 on 2024-12-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dinname',
            field=models.CharField(default='DIN', max_length=255, verbose_name='Din Adı'),
        ),
        migrations.AddField(
            model_name='product',
            name='isoname',
            field=models.CharField(default='ISO', max_length=255, verbose_name='İso Adı'),
        ),
    ]
