# Generated by Django 5.1.3 on 2024-12-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='created_at',
        ),
    ]
